on:
  push:
    paths: 
      - 'web/**'
    branches: ["main"]

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # GCP 인증
      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.KDT1FINAL }}
      # docker 로그인      
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker      


      # Docker build
      - name: Build Docker image
        run: |
          docker build -t gcr.io/kdt1-finalproject/njs-web:web-${{ github.sha }} -f web/Dockerfile web

      # Docker push
      - name: Push Docker image
        run: |
          docker push gcr.io/kdt1-finalproject/njs-web:web-${{ github.sha }}

      # k8s 레포 checkout
      - name: Checkout k8s repo
        uses: actions/checkout@v4
        with:
          repository: whitecode123/k8s
          token: ${{ secrets.learnk8scicd }}
          path: k8s 

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: gcr.io/kdt1-finalproject/njs-web:.*|image: gcr.io/kdt1-finalproject/njs-web:web-${{ github.sha }}|" k8s/web/pod-web.yaml
          
      - name: Set git config
        run: | 
          git config --global user.name "junseorho"
          git config --global user.email "nojun1217429@gmail.com" 
      
      - name: commit and push
        run: |
          cd k8s
          git remote set-url origin https://github.com/whitecode123/k8s.git
          git add web/pod-web.yaml
          git commit -m "Auto update image tag to ${{ github.sha }}"
          git push origin main
        env: 
          GIT_AUTHOR_NAME: junseorho
          GIT_AUTHOR_EMAIL: nojun1217429@gmail.com
          GIT_COMMITTER_NAME: junseorho
          GIT_COMMITTER_EMAIL: nojun1217429@gmail.com    
      
