on:
  push:
    branches: ["main"]

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # GCP 인증
      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.KDT1FINAL }}

      # k8s 레포 checkout
      - name: Checkout k8s repo
        uses: actions/checkout@v4
        with:
          repository: whitecode123/k8s
          token: ${{ secrets.learnk8scicd}}
          path: k8s/web

      # deployment.yaml 이미지 태그 변경
      - name: Update image tag in deployment.yaml
        run: |
             sed -i "s|image: gcr.io/kdt1-finalproject/njs-web:.*|image: gcr.io/kdt1-finalproject/njs-web:web-${{github.sha}}|" k8s/web/pod-web.yaml
      # PR 생성
      - name: Create Pull Request to k8s repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.learnk8scicd }}
          commit-message: "Update image tag to ${{ github.sha }}"
          title: "Update image tag to ${{ github.sha }}"
          body: "Auto PR: Update image tag to ${{ github.sha }}"
          branch: "auto/update-image-${{ github.sha }}"
          path: k8s/web
